//
//  SPStyleKit.h
//  SwiftXcode
//
//  Created by Helge Heß on 01.03.18.
//  Copyright © 2018 ZeeZide GmbH. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <Cocoa/Cocoa.h>



typedef enum : NSInteger
{
    SPStyleKitResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    SPStyleKitResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    SPStyleKitResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    SPStyleKitResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} SPStyleKitResizingBehavior;

extern NSRect SPStyleKitResizingBehaviorApply(SPStyleKitResizingBehavior behavior, NSRect rect, NSRect target);


@interface SPStyleKit : NSObject

// Generated Images
+ (NSImage*)imageOfTableTBImage;
+ (NSImage*)imageOfRawTBImage;
+ (NSImage*)imageOfResolvingTVIcon2;
+ (NSImage*)imageOfFetchDoneTVIcon;
+ (NSImage*)imageOfFetchingTVIcon2;
+ (NSImage*)imageOfCloningTVIcon2;
+ (NSImage*)imageOfCompileDoneTVIcon;
+ (NSImage*)imageOfErrorTVIcon;

@end
